routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PagesController@main")->name("main");
Route::get("/reports", "ReportsController@index")->name("reports");
Route::get("/privacy", "PagesController@privacy")->name("privacy");
Route::get("/disclaimer", "PagesController@disclaimer")->name("disclaimer");

// Disabling Auth::routes() and only make login and logout accessible

Route::get('login', 'Auth\LoginController@login')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Protected routes

// Show administration

// Route::middleware("can:administration")->name("admin")->group(
//   function () {
//     Route::get("/administration", "PagesController@index");
//   }
// );

// namespace directs to the path/folder
// prefix = adds the word to the URL
// name = adds the word to the routes (helpful for app structuring in bigger apps)
// middleware takes the gate "administration" from AuthServiceProvider

// Show, edit & delete users

Route::namespace("Admin")->prefix("admin")->name("admin.")->middleware("can:administration")->group(function () {
  Route::resource("/users", "UsersController", ["except" => ["create", "show", "store"]]);
});

// Add users

Route::namespace("Auth")->prefix("admin/user")->middleware("can:administration")->group(function () {

  Route::get("/add", "RegisterController@showRegistrationForm")->name("admin.user.create");
  Route::post("/add", "RegisterController@register");
});

// Add, edit & delete reports, edit content from main page 

Route::prefix("admin")->middleware("can:administration")->name("admin.")->group(function () {
  Route::match(['put', 'patch'], "reports/multiupdate", "ReportsController@MultipleUpate")->name("reports.multiupdate");
  Route::match(['put', 'patch'], "reports/checkboxupdate", "ReportsController@CheckBoxUpdate")->name("reports.checkboxupdate");
  Route::resource("/reports", "ReportsController", ["except" => ["create", "show"]]);
  Route::resource("/content", "ContentController", ["except" => ["index", "show", "create", "destroy", "store"]]);
});

// Show & download files

Route::middleware("auth")->group(function () {

  Route::get("/folders", "FileController@index")->name("files.index");
  Route::get("files/{file}", "FileController@showCommonFiles")->name("files.show");
  Route::get("/document/{id}", "FileController@downloadSingleFile")->name("file.get");
  Route::get("/personalfiles", "FileController@showPersonalFiles")->name("personalFiles.show");
});

// Add, edit, move & delete files

Route::middleware("can:administration")->name("admin.")->group(function () {
  Route::resource("/admin/file", "FileController", ["except" => ["index", "show", "destroy"]]);
  Route::get("/userfiles/{id}", "FileController@showUserFiles")->name("userFiles.show");
  Route::get("/admin/folder/file/{id}", "FileController@addFileToFolder")->name("addFileToFolder");
  Route::match(["put", "delete"], "filesDeleteOrMove", "FileController@filesDeleteOrMove")->name("filesDeleteOrMove");
});

// Add, edit & delete folder

Route::middleware("can:administration")->name("admin.")->group(function () {
  Route::resource("/admin/folder", "FolderController", ["except" => ["index", "show", "destroy"]]);
  Route::delete("/folders/{id}", "FolderController@destroy")->name("folder.destroy");
});

resources/views/admin/index.blade.php
{{-- Not used anymore. Maybe later again? --}}

@extends('layouts.app')

@section('content')
<h2>Verwaltung</h2>
<a class="floating-add-file" href="{{route("admin.file.create")}}">
  <x-svg svg="file" fill="#000000" viewBox="24 24" class="file-svg"/>
</a>
<div class="admin-nav">
  <a class="admin-nav-link" href="{{route("admin.users.index")}}">Benutzerverwaltung</a>

  <a class="admin-nav-link" href="{{route("admin.user.create")}}">Benutzer hinzufügen</a>

  <a class="admin-nav-link" href="{{route("admin.reports.index")}}">Feedbackverwaltung</a>

  <a class="admin-nav-link" href="{{route("files.index")}}">Dateiverwaltung</a>
</div>


@if(count($newReports) > 0)

<h2>Neue Feedback Einträge</h2>

{!! Form::open(["route" => ["admin.reports.multiupdate"], "method" => "PUT", "class" => "report-table"]) !!}
<div class="th-row">
  <div class="th-author">Name</div>
  <div class="th-flex">Feedback</div>
  <div class="th-wrapper">
    <div class="th-visible">
      <p class="th-text">Sichtbar</p>
    </div>
    <div class="th-slider">
      <p class="th-text">Im Slider</p>
    </div>
    <div class="th-small">Bearbeiten</div>
  </div>
</div>


@foreach ($newReports as $newReport)
<div class="report-tr">
  <input type="hidden" name="reports[{{$loop->index}}][id]" value="{{$newReport->id}}">
  <div class="td-name">
    <p class="td-text">{{$newReport->name}}</p>
    <div class="show-star-rating-sm" style="--rating: {{$newReport->rating}}">
    </div>
    <div class="show-star-rating-l" style="--rating: {{$newReport->rating}}">
    </div>
  </div>
  <div class="td-flex">{{$newReport->body}}</div>
  <div class="tr-wrapper">
    <div class="form-wrapper">
      <div class="checkbox-wrapper">
        <div class="checkbox-visible">
          <div class="checkbox-container">
            <input class="checkbox" type="checkbox" name="reports[{{$loop->index}}][visible]" value="1" checked>
            <span class="checkmark"></span>
          </div>
          <label class="table-label" for="visible">Sichtbar</label>
        </div>
        <div class="checkbox-slider">
          <div class="checkbox-container">
            <input class="checkbox" type="checkbox" name="reports[{{$loop->index}}][show_in_slider]" value="1"
              {{($newReport->show_in_slider == 1 ? "checked" : "")}}>
            <span class="checkmark"></span>
          </div>
          <label class="table-label" for="show_in_slider">Im Slider</label>
        </div>

      </div>
    </div>

    <a class="table-link table-edit" href={{route("admin.reports.edit", $newReport->id)}}>
      <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="table-svg" />
    </a>

  </div>
</div>
@endforeach
<button class="floating-save">
  <x-svg svg="saveAll" id="path90" height="36" width="36" viewBox="32 32" class="saveAll" />
</button>
{!! Form::close() !!}

@endif

@endsection