routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PagesController@main")->name("main");
Route::get("/reports", "ReportsController@index")->name("reports");
Route::get("/privacy", "PagesController@privacy")->name("privacy");
Route::get("/disclaimer", "PagesController@disclaimer")->name("disclaimer");

// Disabling Auth::routes() and only make login and logout accessible

Route::get('login', 'Auth\LoginController@login')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Protected routes

// Show administration

// Route::middleware("can:administration")->name("admin")->group(
//   function () {
//     Route::get("/administration", "PagesController@index");
//   }
// );

// namespace directs to the path/folder
// prefix = adds the word to the URL
// name = adds the word to the routes (helpful for app structuring in bigger apps)
// middleware takes the gate "administration" from AuthServiceProvider

// Show, edit & delete users

Route::namespace("Admin")->prefix("admin")->name("admin.")->middleware("can:administration")->group(function () {
  Route::resource("/users", "UsersController", ["except" => ["create", "show", "store"]]);
});

// Add users

Route::namespace("Auth")->prefix("admin/user")->middleware("can:administration")->group(function () {

  Route::get("/add", "RegisterController@showRegistrationForm")->name("admin.user.create");
  Route::post("/add", "RegisterController@register");
});

// Add, edit & delete reports, edit content from main page 

Route::prefix("admin")->middleware("can:administration")->name("admin.")->group(function () {
  Route::match(['put', 'patch'], "reports/multiupdate", "ReportsController@MultipleUpate")->name("reports.multiupdate");
  Route::match(['put', 'patch'], "reports/checkboxupdate", "ReportsController@CheckBoxUpdate")->name("reports.checkboxupdate");
  Route::resource("/reports", "ReportsController", ["except" => ["create", "show"]]);
  Route::resource("/content", "ContentController", ["except" => ["index", "show", "create", "destroy", "store"]]);
});

// Show & download files

Route::middleware("auth")->group(function () {

  Route::get("/folders", "FileController@index")->name("files.index");
  Route::get("files/{file}", "FileController@showCommonFiles")->name("files.show");
  Route::get("/document/{id}", "FileController@downloadSingleFile")->name("file.get");
  Route::get("/personalfiles", "FileController@showPersonalFiles")->name("personalFiles.show");
});

// Add, edit, move & delete files

Route::middleware("can:administration")->name("admin.")->group(function () {
  Route::resource("/admin/file", "FileController", ["except" => ["index", "show", "destroy"]]);
  Route::get("/userfiles/{id}", "FileController@showUserFiles")->name("userFiles.show");
  Route::get("/admin/folder/file/{id}", "FileController@addFileToFolder")->name("addFileToFolder");
  Route::match(["put", "delete"], "filesDeleteOrMove", "FileController@filesDeleteOrMove")->name("filesDeleteOrMove");
});

// Add, edit & delete folder

Route::middleware("can:administration")->name("admin.")->group(function () {
  Route::resource("/admin/folder", "FolderController", ["except" => ["index", "show", "destroy"]]);
  Route::delete("/folders/{id}", "FolderController@destroy")->name("folder.destroy");
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

// bring in for caching current online users

use Illuminate\Support\Facades\Cache;

class User extends Authenticatable
{
  use Notifiable;

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'name', 'password',
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
    'password', 'remember_token',
  ];

  /**
   * The attributes that should be cast to native types.
   *
   *  // For checking the users last online time
   * 
   * @var array
   */
  protected $casts = [
    "last_online_at" => "datetime",
  ];

  // checking for current online users

  public function isOnline()
  {
    return Cache::has('user-is-online-' . $this->id);
  }


  // This function defines, that this model belongs to the Role model

  public function roles()
  {
    return $this->belongsToMany("App\Role");
  }

  // methods for checking roles of users

  public function roleControl($roles)
  {

    if ($this->roles()->whereIn("role", $roles)->first()) {
      return true;
    }
    return false;
  }


  public function hasRole($role)
  {

    if ($this->roles()->where("role", $role)->first()) {
      return true;
    }
    return false;
  }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

use App\User;
use App\Role;
use App\File;
use App\Http\Requests\UpdateUser;

class UsersController extends Controller
{

  public function __construct()
  {
    $this->middleware("auth");
  }
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $users = User::all();

    $users->each(function (user $user) {
      $count = File::where("userID", $user->id)->count();
      $user->count = $count;
    });

    return view("admin.users.index")->with("users", $users);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    //
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    //
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\User  $user
   * @return \Illuminate\Http\Response
   */
  public function show(User $user)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\User  $user
   * @return \Illuminate\Http\Response
   */
  public function edit(User $user)
  {
    $roles = Role::all();

    return view("admin.users.edit")->with([
      "user" => $user,
      "roles" => $roles
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\User  $user
   * @return \Illuminate\Http\Response
   */
  public function update(UpdateUser $request, User $user)
  {
    $current_user = Auth::User()->id;
    $requested_user = $user->id;

    // check if the current user wants to delete his admin rights

    if ($current_user == $requested_user) {
      $roles = $request->input("roles");

      $isAdmin = "1";

      $exists = in_array($isAdmin, $roles);

      if ($exists == FALSE) {
        $request->session()->flash("error", "Du kannst deine Adminrechte nicht löschen!");
        return redirect("admin/users/$user->id/edit");
      }
    }

    //Save roles
    $user->roles()->sync($request->input("roles"));

    //Save user
    if ($request->input("name")) {
      $user->name = $request->input("name");
    }

    if ($request->input('password')) {
      $user->password = Hash::make($request->input('password'));
    }

    if ($user->save()) {
      $request->session()->flash("success", $user->name . " erfolgreich gespeichert!");
    };
    return redirect()->route("admin.users.index");
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\User  $user
   * @return \Illuminate\Http\Response
   */
  public function destroy(User $user)
  {
    $current_user = Auth::User()->id;
    $requested_user = $user->id;

    if ($requested_user == $current_user) {
      return redirect()->route("admin.users.index")->with("error", "Du kannst deinen eigenen Account nicht löschen!");
    } else {

      $user->roles()->detach();

      $filesExist = File::all()->contains("userID", $user->id);

      if ($filesExist == true) {
        File::where("userID", $user->id)->delete();

        Storage::disk("local")->deleteDirectory("files/userID_" . $user->id);
      }

      if ($user->delete()) {
        return redirect()->route("admin.users.index")->with("success", "'$user->name'" . " gelöscht!");
      }
    }
  }
}

resources/views/admin/users/add.blade.php
@extends('layouts.app')


@section('content')

@include("inc.backButton")

<h2>Benutzer Erstellen</h2>
<div class="form-container">
  {!! Form::open(["route" => "admin.user.create", "method" => "POST"]) !!}

  <h3>Neuen Benutzer anlegen</h3>

  @include('admin.users.inc.userForm')

  <div class="row-space-between margin-30 top"><a class="abort-btn" href="{{route("admin.users.index")}}">Abbrechen</a>
    <button class="action-btn" type="submit">Nutzer anlegen</button>
  </div>
  {!! Form::close() !!}
</div>


@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

@include("inc.backButton")

<h2>User bearbeiten</h2>

{!! Form::open(["route" => ["admin.users.update", $user], "method" => "POST", "class" => "form-container"]) !!}


<h3>"{{$user->name}}" bearbeiten</h3>

@include("admin.users.inc.userForm")

{{Form::hidden("_method", "PUT")}}
<div class="row-space-between margin-30 top"><a class="abort-btn" href="{{route("admin.users.index")}}">Abbrechen</a>
  <button class="action-btn">Speichern</button>
</div>
{!! Form::close() !!}


@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')

@include("inc.backButton")

<h2>Benutzerverwaltung</h2>

<div class="row">
  <a class="action-btn" href="{{route("admin.user.create")}}">Benutzer hinzufügen</a>
</div>


<table class="table">
  <thead>
    <tr>
      <th class="th">Name</th>
      <th class="th">Status</th>
      <th class="th">Zuletzt online</th>
      <th class="th">Rechte</th>
      <th class="th">Aktionen</th>
    </tr>
  </thead>
  <tbody>

    @foreach ($users as $user)
    <tr class="tr">

      <td class="td"><a class="table-link-color" href={{route("admin.userFiles.show", $user->id)}}>{{$user->name}}
          ({{$user->count}})</a>
      </td>

      @if ($user->isOnline())
      <td class="td-online">online</td>
      @else
      <td class="td-offline">offline</td>
      @endif

      <td class="td">{{$user->last_online_at->translatedFormat("D, j.m.y, H:i")}} Uhr</td>
      <td class="td">{{ implode(", ", $user->roles()->get()->pluck("role")->toArray()) }}</td>

      <td class="td">
        <div class="td-actions">
          <a class="table-link" href={{route("admin.users.edit", $user->id)}}>
            <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="edit"/></a>
          <button class="table-button" onclick="ToggleDeleteModal({{$user}})" id="toggleDeleteIsNecessary">
            <x-svg svg="trash" width=36 height=36 viewBox="24 24" class="delete"/>
          </button>
        </div>
      </td>


    </tr>

    @endforeach

  </tbody>
</table>
@endsection