routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PagesController@main")->name("main");
Route::get("/reports", "ReportsController@index")->name("reports");
Route::get("/privacy", "PagesController@privacy")->name("privacy");
Route::get("/disclaimer", "PagesController@disclaimer")->name("disclaimer");

// Disabling Auth::routes() and only make login and logout accessible

Route::get('login', 'Auth\LoginController@login')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Protected routes

// Show administration

// Route::middleware("can:administration")->name("admin")->group(
//   function () {
//     Route::get("/administration", "PagesController@index");
//   }
// );

// namespace directs to the path/folder
// prefix = adds the word to the URL
// name = adds the word to the routes (helpful for app structuring in bigger apps)
// middleware takes the gate "administration" from AuthServiceProvider

// Show, edit & delete users

Route::namespace("Admin")->prefix("admin")->name("admin.")->middleware("can:administration")->group(function () {
  Route::resource("/users", "UsersController", ["except" => ["create", "show", "store"]]);
});

// Add users

Route::namespace("Auth")->prefix("admin/user")->middleware("can:administration")->group(function () {

  Route::get("/add", "RegisterController@showRegistrationForm")->name("admin.user.create");
  Route::post("/add", "RegisterController@register");
});

// Add, edit & delete reports, edit content from main page 

Route::prefix("admin")->middleware("can:administration")->name("admin.")->group(function () {
  Route::match(['put', 'patch'], "reports/multiupdate", "ReportsController@MultipleUpate")->name("reports.multiupdate");
  Route::match(['put', 'patch'], "reports/checkboxupdate", "ReportsController@CheckBoxUpdate")->name("reports.checkboxupdate");
  Route::resource("/reports", "ReportsController", ["except" => ["create", "show"]]);
  Route::resource("/content", "ContentController", ["except" => ["index", "show", "create", "destroy", "store"]]);
});

// Show & download files

Route::middleware("auth")->group(function () {

  Route::get("/folders", "FileController@index")->name("files.index");
  Route::get("files/{file}", "FileController@showCommonFiles")->name("files.show");
  Route::get("/document/{id}", "FileController@downloadSingleFile")->name("file.get");
  Route::get("/personalfiles", "FileController@showPersonalFiles")->name("personalFiles.show");
});

// Add, edit, move & delete files

Route::middleware("can:administration")->name("admin.")->group(function () {
  Route::resource("/admin/file", "FileController", ["except" => ["index", "show", "destroy"]]);
  Route::get("/userfiles/{id}", "FileController@showUserFiles")->name("userFiles.show");
  Route::get("/admin/folder/file/{id}", "FileController@addFileToFolder")->name("addFileToFolder");
  Route::match(["put", "delete"], "filesDeleteOrMove", "FileController@filesDeleteOrMove")->name("filesDeleteOrMove");
});

// Add, edit & delete folder

Route::middleware("can:administration")->name("admin.")->group(function () {
  Route::resource("/admin/folder", "FolderController", ["except" => ["index", "show", "destroy"]]);
  Route::delete("/folders/{id}", "FolderController@destroy")->name("folder.destroy");
});

resources/views/pages/disclaimer.blade.php
@extends('layouts.app')

@section('content')

<h1>Impressum</h1>

<h2>Technische Umsetzung</h2>
<p class="lh-m">Leon Pelzer<br>
  E-Mail:
  <a class="basic-link" href="mailto:leonpe@web.de">leonpe@web.de</a><br>
  GitLab Profil:
  <a class="basic-link" href="https://gitlab.com/leonp5" target="_blank">Hier entlang</a>
</p>

<h2>Angaben gem&auml;&szlig; &sect; 5 TMG</h2>
<p class="lh-m">David Menrath<br />
  Senefelderstra&szlig;e 16<br />
  50825 K&ouml;ln</p>

<h2>Kontakt</h2>
{{-- <p>Telefon: {{ env('HANDY_NR') }}<br /> --}}
<p>
  E-Mail: <a class="basic-link" href="mailto:david.menrath@gmail.com">david.menrath@gmail.com</a></p>

{{-- <h2>Verbraucher&shy;streit&shy;beilegung/Universal&shy;schlichtungs&shy;stelle</h2>
<p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle
  teilzunehmen.</p> --}}

<h3>Haftung f&uuml;r Inhalte</h3>
<p>Als Diensteanbieter bin ich gem&auml;&szlig; &sect; 7 Abs.1 TMG f&uuml;r eigene Inhalte auf diesen Seiten nach den
  allgemeinen Gesetzen verantwortlich. Nach &sect;&sect; 8 bis 10 TMG bin ich als Diensteanbieter jedoch nicht
  verpflichtet, &uuml;bermittelte oder gespeicherte fremde Informationen zu &uuml;berwachen oder nach Umst&auml;nden zu
  forschen, die auf eine rechtswidrige T&auml;tigkeit hinweisen.</p>
<p>Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben
  hiervon unber&uuml;hrt. Eine diesbez&uuml;gliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten
  Rechtsverletzung m&ouml;glich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werde ich diese Inhalte
  umgehend entfernen.</p>
<h3>Haftung f&uuml;r Links</h3>
<p>Mein Angebot enth&auml;lt Links zu externen Websites Dritter, auf deren Inhalte ich keinen Einfluss habe. Deshalb
  kann ich f&uuml;r diese fremden Inhalte auch keine Gew&auml;hr &uuml;bernehmen. F&uuml;r die Inhalte der
  verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten
  wurden zum Zeitpunkt der Verlinkung auf m&ouml;gliche Rechtsverst&ouml;&szlig;e &uuml;berpr&uuml;ft. Rechtswidrige
  Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.</p>
<p>Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer
  Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werde ich derartige Links umgehend
  entfernen.</p>
<h3>Urheberrecht</h3>
<p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht.
  Die Vervielf&auml;ltigung, Bearbeitung, Verbreitung und jede Art der Verwertung au&szlig;erhalb der Grenzen des
  Urheberrechtes bed&uuml;rfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien
  dieser Seite sind nur f&uuml;r den privaten, nicht kommerziellen Gebrauch gestattet.</p>
<p>Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet.
  Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung
  aufmerksam werden, bitte ich um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werde ich
  derartige Inhalte umgehend entfernen.</p>

<p>Quelle: <a class="basic-link" href="https://www.e-recht24.de">eRecht24</a></p>

<div class="row-wrap">
  <div class="column margin-50">
    <h3>Fotos</h3>
    <p class="center-text">Header Bild auf der Startseite von <a class="basic-link"
        href="https://pixabay.com/de/users/Pixapopz-2873171/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1547018"
        target="_blank">Chuk
        Yong</a> auf <a class="basic-link"
        href="https://pixabay.com/de/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1547018"
        target="_blank">Pixabay</a>
    </p>
  </div>
  <div class="column margin-50">
    <h3>Icons & Grafiken</h3>
    <p class="center-text">"Tafel mit Apfel" von <a class="basic-link"
        href="https://pixabay.com/de/users/Clker-Free-Vector-Images-3736/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=23421"
        target="_blank">Clker-Free-Vector-Images</a>
      auf <a class="basic-link"
        href="https://pixabay.com/de/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=23421"
        target="_blank">Pixabay</a>
    </p>
    <p>
      WhatsApp Icon: <a class="basic-link" href="https://de.wikipedia.org/wiki/Datei:WhatsApp.svg"
        target="_blank">Wikipedia</a>
    </p>
    <p>
      Telegram Icon: <a class="basic-link" href="https://de.wikipedia.org/wiki/Datei:Telegram_logo.svg"
        target="_blank">Wikipedia</a>
    </p>

    <p class="center-text">
      <x-svg svg="folder" fill="#000000" width=26 height=26 viewBox="26 26" class="disclaimer-svg" />
      und
      <x-svg svg="file" fill="#000000" viewBox="24 24" class="disclaimer-svg" />
      Icon
      von
      <a class="basic-link" href="https://icons8.com" target="_blank">
        Icons8</a> </p>
    <p class="center-text">
      <x-svg svg="save" width=36 height=36 viewBox="512 512" class="disclaimer-svg" />

      Icon von
      <a class="basic-link" href="https://www.flaticon.com/authors/freepik" target="_blank">
        Freepik </a> auf <a class="basic-link" target="_blank" href="https://www.flaticon.com/">Flaticon</a></p>

    <p class="center-text">
      <x-svg svg="call" width=36 height=36 viewBox="512.076 512.076" class="disclaimer-svg" />
      und
      <x-svg svg="email" width=36 height=36 viewBox="511.974 511.974" class="disclaimer-svg" />
      Icon von
      <a class="basic-link" href="https://www.flaticon.com/authors/smashicons" target="_blank">
        Smashicons</a> auf <a class="basic-link" target="_blank" href="https://www.flaticon.com/">Flaticon</a></p>

    <p class="center-text">
      <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="disclaimer-svg" />
      und
      <x-svg svg="trash" fill="none" width=36 height=36 viewBox="24 24" class="disclaimer-svg" />
      von <a class="basic-link" target="_blank" href="https://twitter.com/steveschoger">
        Steve Shoger</a> und <a class="basic-link" href="https://twitter.com/adamwathan" target="_blank">Adam Wathan</a>
      auf
      <a class="basic-link" href="https://heroicons.dev/" target="_blank">
        heroicons.dev</a> </p>

    <p class="center-text">
      <x-svg svg="plus" viewBox="469.33333 469.33333" class="disclaimer-svg" />
      von
      <a class="basic-link" href="https://www.flaticon.com/authors/pixel-perfect" target="_blank">
        Pixel perfect</a> auf <a class="basic-link" target="_blank" href="https://www.flaticon.com">Flaticon</a> </p>

    <p class="center-text">
      <x-svg svg="saveAll" id="path90" height="36" width="36" viewBox="32 32" class="disclaimer-svg" />
      von
      <a class="basic-link" href="https://commons.wikimedia.org/wiki/File:Breezeicons-actions-32-document-save-all.svg"
        target="_blank">
        Wikipedia</a> </p>

    <p class="center-text">
      <x-svg svg="copy" fill="none" width=36 height=36 viewBox="368.008 368.008" class="copy" />
      von <a class="basic-link" href="https://www.flaticon.com/authors/vitaly-gorbachev" target="_blank">Vitaly
        Gorbachev</a> von <a class="basic-link" href="https://www.flaticon.com" target="_blank">Flaticon</a>
    </p>
  </div>

</div>


@endsection

resources/views/pages/main.blade.php
@extends('layouts.app')

@section('headerimage')

@if($content ?? "")

<div class="img-container">

  <div class="main-img-text-container">
    @can('administration')
    <div class="align-right"><a class="table-button" href="{{route("admin.content.edit", $content[4]->id)}}">
        <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="edit-active" />
      </a>
    </div>
    @endcan

    <h2 class="badge-heading">{{$content[4]->title}}</h2>
    <h2 class="badge-heading">{{$content[4]->body}}</h2>
    <h2 class="badge-heading">{{$content[4]->email}}</h2>
  </div>
  <div class="slider-container mq-max-m" id="desktop-slider">
    @include('pages.inc.slider')
  </div>

  <img class="header-image" src="{{asset("storage/images/home_1400.jpg")}}" alt="Mathe Nachhilfe Köln">
  <div class="img-overlay-white"></div>
  <div class="img-overlay-transparent"></div>
</div>
@else

<p>Es gibt keinen Content in der Datenbank!</p>

@endif

@endsection

{{-- put the modal here, because inside of the content section it only takes the half of the screen and i don't know why --}}

@include('inc.imageModal')

@section('content')

@if($content ?? "")

<div class="slider-container mq-min-m" id="mobile-slider">
  @include('pages.inc.slider')
</div>

@can('administration')

<div class="align-right"><a class="table-button" href="{{route("admin.content.edit", $content[0]->id)}}">
    <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="edit-active" />
  </a>
</div>

@endcan

<h2 class="h2" id="start">{{$content[0]->title}}</h2>
<div class="svg-text-wrapper">
  <x-svg svg="blackboard" width=100 height=100 viewBox="575 700" class="blackboard-svg float-left" />
  <p>
    {{$content[0]->body}}
  </p>
</div>
@can('administration')

<div class="align-right"><a class="table-button" href="{{route("admin.content.edit", $content[1]->id)}}">
    <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="edit-active" />
  </a>
</div>

@endcan

<h2 class="h2" id="lerninhalte">{{$content[1]->title}}</h2>
<p class="desktop-flex-reverse">
  <img class="content-img-right float-right" src="{{asset("storage/images/mathe-endlich_250.jpg")}}">
  {{$content[1]->body}}
</p>

@can('administration')

<div class="align-right"><a class="table-button" href="{{route("admin.content.edit", $content[2]->id)}}">
    <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="edit-active" />
  </a>
</div>

@endcan

<h2 class="h2" id="uebermich">{{$content[2]->title}}</h2>

<p class="desktop-flex">
  <a onClick="ToggleImage()" class="toggle-img-btn">
    <img class="content-img-left float-left" src="{{asset("storage/images/david_menrath_bueffelhilfe_170.jpg")}}"
      alt="foto_david_menrath" /></a>
  {{$content[2]->body}}</p>
@can('administration')

<div class="align-right"><a class="table-button" href="{{route("admin.content.edit", $content[3]->id)}}">
    <x-svg svg="pencil" fill="none" width=36 height=36 viewBox="24 24" class="edit-active" />
  </a>
</div>

@endcan

<h2 class="h2" id="kontakt">{{$content[3]->title}}</h2>
<div class="contact-box">
  <div class="contact-row"><a class="invisible-anchor" href="{{ env('WA_LINK') }}" target="_blank" rel="noopener">
      <img class="wa-img" src="{{asset("storage/images/WhatsApp.png")}}">
      <a class="invisible-anchor" href="{{ env('TELEGRAM_LINK') }}" target="_blank" rel="noopener">
        <img class="telegram-img" src="{{asset("storage/images/Telegram.png")}}">
      </a>
    </a></div>
  <div class="contact-row">
    <x-svg svg="call" width=36 height=36 viewBox="512.076 512.076" class="contact-svg" />
    <p class="contact-text">{{$content[3]->body}}</p>
  </div>
  <div class="contact-row">
    <x-svg svg="email" width=36 height=36 viewBox="511.974 511.974" class="contact-svg" />
    <p class="contact-text"><a class="basic-link" href="mailto:{{$content[3]->email}}">{{$content[3]->email}}</a></p>
  </div>
</div>

@else

<p>Es gibt keinen Content in der Datenbank!</p>

@endif

@include('inc.contactMap')

@endsection

resources/views/pages/privacy.blade.php
@extends('layouts.app')

@section('content')

<h2>Datenschutz</h2>

<h3 class="center-text">Allgemeiner Hinweis und Pflichtinformationen</h3>
<h3 class="center-text">Benennung der verantwortlichen Stelle</h3>
<p>Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:</p>
<p>David Menrath<br>Senefelderstraße 16<br>50825, Köln</p>
<p>Die verantwortliche Stelle entscheidet allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung
  von personenbezogenen Daten (z.B. Namen, Kontaktdaten o. Ä.).</p>

<h3 class="center-text">Widerruf Ihrer Einwilligung zur Datenverarbeitung</h3>
<p>Nur mit Ihrer ausdrücklichen Einwilligung sind einige Vorgänge der Datenverarbeitung möglich. Ein Widerruf Ihrer
  bereits erteilten Einwilligung ist jederzeit möglich. Für den Widerruf genügt eine formlose Mitteilung per E-Mail. Die
  Rechtmäßigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unberührt.</p>

<h3 class="center-text">Recht auf Beschwerde bei der zuständigen Aufsichtsbehörde</h3>
<p>Als Betroffener steht Ihnen im Falle eines datenschutzrechtlichen Verstoßes ein Beschwerderecht bei der zuständigen
  Aufsichtsbehörde zu. Zuständige Aufsichtsbehörde bezüglich datenschutzrechtlicher Fragen ist der
  Landesdatenschutzbeauftragte des Bundeslandes, in dem sich der Sitz unseres Unternehmens befindet. Der folgende Link
  stellt eine Liste der Datenschutzbeauftragten sowie deren Kontaktdaten bereit: <a
    href="https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html"
    target="_blank">https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html</a>.</p>

<h3 class="center-text">Recht auf Datenübertragbarkeit</h3>
<p>Ihnen steht das Recht zu, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags
  automatisiert verarbeiten, an sich oder an Dritte aushändigen zu lassen. Die Bereitstellung erfolgt in einem
  maschinenlesbaren Format. Sofern Sie die direkte Übertragung der Daten an einen anderen Verantwortlichen verlangen,
  erfolgt dies nur, soweit es technisch machbar ist.</p>

<h3 class="center-text">Recht auf Auskunft, Berichtigung, Sperrung, Löschung</h3>
<p>Sie haben jederzeit im Rahmen der geltenden gesetzlichen Bestimmungen das Recht auf unentgeltliche Auskunft über Ihre
  gespeicherten personenbezogenen Daten, Herkunft der Daten, deren Empfänger und den Zweck der Datenverarbeitung und
  ggf. ein Recht auf Berichtigung, Sperrung oder Löschung dieser Daten. Diesbezüglich und auch zu weiteren Fragen zum
  Thema personenbezogene Daten können Sie sich jederzeit über die im Impressum aufgeführten Kontaktmöglichkeiten an uns
  wenden.</p>

<h3 class="center-text">SSL- bzw. TLS-Verschlüsselung</h3>
<p>Aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, die Sie an uns als Seitenbetreiber
  senden, nutzt unsere Website eine SSL-bzw. TLS-Verschlüsselung. Damit sind Daten, die Sie über diese Website
  übermitteln, für Dritte nicht mitlesbar. Sie erkennen eine verschlüsselte Verbindung an der „https://“ Adresszeile
  Ihres Browsers und am Schloss-Symbol in der Browserzeile.</p>

<h3 class="center-text">Server-Log-Dateien</h3>
<p>In Server-Log-Dateien erhebt und speichert der Provider der Website automatisch Informationen, die Ihr Browser
  automatisch an uns übermittelt. Dies sind:</p>
<ul>
  <li>Besuchte Seite auf unserer Domain</li>
  <li>Datum und Uhrzeit der Serveranfrage</li>
  <li>Browsertyp und Browserversion</li>
  <li>Verwendetes Betriebssystem</li>
  <li>Referrer URL</li>
  <li>Hostname des zugreifenden Rechners</li>
  <li>IP-Adresse</li>
</ul>
<p>Es findet keine Zusammenführung dieser Daten mit anderen Datenquellen statt. Grundlage der Datenverarbeitung bildet
  Art. 6 Abs. 1 lit. b DSGVO, der die Verarbeitung von Daten zur Erfüllung eines Vertrags oder vorvertraglicher
  Maßnahmen gestattet.</p>

<h3 class="center-text">Speicherdauer von Beiträgen und Kommentaren</h3>
<p>Beiträge und Kommentare sowie damit in Verbindung stehende Daten, wie beispielsweise IP-Adressen, werden gespeichert.
  Der Inhalt verbleibt auf unserer Website, bis er vollständig gelöscht wurde oder aus rechtlichen Gründen gelöscht
  werden musste.</p>
<p>Die Speicherung der Beiträge und Kommentare erfolgt auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO).
  Ein Widerruf Ihrer bereits erteilten Einwilligung ist jederzeit möglich. Für den Widerruf genügt eine formlose
  Mitteilung per E-Mail. Die
  Rechtmäßigkeit bereits erfolgter Datenverarbeitungsvorgänge bleibt vom Widerruf unberührt.</p>
<p><small>Quelle: Datenschutz-Konfigurator von <a class="basic-link" href="http://www.mein-datenschutzbeauftragter.de"
      target="_blank">mein-datenschutzbeauftragter.de</a></small></p>

@endsection